image: cengwins/ahc-uhd-image
command: /bin/sh -c "
  pip install adhocomputing &&
  python3 General/testcomposition.py &&
  python3 General/test.py &&
  python3 General/testnx.py &&
  python3 General/testchannels.py &&
  python3 main.py"

env:
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"